### ISSUE TITLE
Font Spacing is really bad.

### ISSUE THREAD

**Issue by 3asier** [wilsam239/Untangled#16]
The font width on '1' character is extremely small.  This leads to numbers such as '11' '12' '13' etc. being completely unreadable.

At this point, I think we need to look into modifying this font (this would also be necessary if we wanted to publish the game).  Or finding a similar font,, without spacing issues.

**Comment by wilsam239** [comment]
Font has been modified. The one character should now display fine and the pipe character has also been fixed.
