### ISSUE TITLE
Very low fps on different resolutions.

### ISSUE THREAD

**Issue by 3asier** [wilsam239/Untangled#17]
This is caused by image scaling.  Processing requires lots of time to perform images scaling.  We could work around this issue by exporting several images (one at each of the supported resolutions) so that the scaling doesn't need to be done at runtime.

**Comment by 3asier** [comment]
Added correctly sized images so that they don't have to be scaled at runtime.
These however are poorly scaled and should be replaced by proper versions based off the original vector graphic.

**Comment by wilsam239** [comment]
Images are now correctly scaled with vectorised versions.
