### ISSUE TITLE
Count number of moves to complete

### ISSUE THREAD

**Issue by wilsam239** [wilsam239/Untangled#4]
Add a counter to show the user how many moves they have made. (Every time they successfully select a vertex and move it)

**Comment by wilsam239** [comment]
Move counter has been implemented, just need to display now.

**Comment by 3asier** [comment]
This has been implemented for a while; since https://github.com/wilsam239/Untangled/commit/668b44460e404c9b281a4dfca4255cfd51fe55cc 😄
